[workspace]
resolver = "2"
members = ["crates/kazuka-core"]

[workspace.dependencies]
thiserror = "2.0"
tracing = "0.1"
anyhow = "1.0"

[workspace.dependencies.criterion]
version = "0.6"
features = ["html_reports"]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
features = ["fmt", "env-filter"]
