name: Forge test
description: Run tests
inputs:
  root:
    description: The project's root path
    required: true

runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      env:
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        ALCHEMY_ETHEREUM_MAINNET_RPC_URL: ${{ secrets.ALCHEMY_ETHEREUM_MAINNET_RPC_URL }}
        INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
        INFURA_ETHEREUM_MAINNET_RPC_URL: ${{ secrets.INFURA_ETHEREUM_MAINNET_RPC_URL }}
        FORK_BLOCK_NUMBER: ${{ secrets.FORK_BLOCK_NUMBER }}
      run: |
        forge test --etherscan-api-key "$ETHERSCAN_API_KEY" -vvv --no-restart --root ${{ inputs.root }}
