name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: ./.github/actions/forge_build
        with:
          root: ./crates/strategies/kazuka-mev-share-arbitrage/contracts

      - name: Run forge tests
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ALCHEMY_ETHEREUM_MAINNET_RPC_URL: ${{ secrets.ALCHEMY_ETHEREUM_MAINNET_RPC_URL }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          INFURA_ETHEREUM_MAINNET_RPC_URL: ${{ secrets.INFURA_ETHEREUM_MAINNET_RPC_URL }}
          FORK_BLOCK_NUMBER: ${{ secrets.FORK_BLOCK_NUMBER }}
        run: |
          forge test --etherscan-api-key "$ETHERSCAN_API_KEY" -vvv --no-restart --root ./crates/strategies/kazuka-mev-share-arbitrage/contracts
        id: test
